.Dd December 01, 2022
.Dt XLSROOTS 1
.Sh NAME
.Nm xlsroots
.Nd list every X root window id
.Sh SYNOPSIS
.Nm
.Op Fl v
.Sh OPTIONS
.Bl -tag -width indent
.It Fl v
display the program version
.El
.Sh DESCRIPTION
The
.Nm
utility lets you list every X root window id.
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xlsroots/issues
